#!/usr/bin/env python3
"""pair_correlation.py"""

# Demonstrate Montgomery Pair Correlation Conjecture:
# The spacing between the nontrivial zeros of the Riemann zeta function
# behave statistically like the spacings between eigenvalues of a
# random Hermitian matrix drawn from the Gaussian Unitary Ensemble (GUE)

import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MultipleLocator


def create_gaussian_unitary_ensemble():
    """
    Creates a 100x100 Hermitian matrix with complex off-diagonal entries
    and real diagonal entries.
    The complex off-diagonals are generated by drawing both real
    imaginary parts from a standard normal distribution.
    The real diagonal entries are drawn from a standard normal distribution
    and then multiplied by sqrt(2).

    Returns:
        H (ndarray): A 100x100 Hermitian matrix.
    """
    n = 1000

    # Create a random 100x100 complex matrix.
    # Off-diagonals: real and imaginary parts are drawn from a standard normal distribution.
    A = np.random.randn(n, n) + 1j * np.random.randn(n, n)

    # Form a Hermitian matrix by symmetrizing A: (A + A†)/2 ensures H = H†.
    H = (A + A.conj().T) / 2

    # Replace the diagonal with real Gaussian random numbers multiplied by sqrt(2).
    diagonal = np.random.randn(n) * np.sqrt(2)
    np.fill_diagonal(H, diagonal)

    return H


def main():
    # Read pickle file containing the zeta zeros
    file_path = Path(__file__).parent / "zeta_zeros.pickle"
    with open(file_path, "rb") as file_in:
        zeta_zeros = pickle.load(file_in)
    # Take only the first 1000 zeta zeros
    zeta_zeros = zeta_zeros[:1000]

    # Create a 100x100 GUE matrix and find its 100 real eigenvalues
    gue = create_gaussian_unitary_ensemble()
    eigvals = sorted(np.real_if_close(np.linalg.eigvals(gue), tol=1e-10))

    # Scale the eigenvalues to match the range of the zeta zeros
    emin, emax = min(eigvals), max(eigvals)
    zmin, zmax = zeta_zeros[0], zeta_zeros[-1]
    eigvals = zmin + (eigvals - emin) * (zmax - zmin) / (emax - emin)

    # Create a 1d array of 1000 random floats following a uniform distribution
    random_array = sorted(
        np.random.uniform(low=zeta_zeros[0], high=zeta_zeros[-1], size=1000)
    )

    # Plot the Zeta Zeros in 10 lines of 100 values each
    once = True
    plt.figure(Path(__file__).name)
    for i in range(10):
        start = i * 100
        stop = start + 99
        x = zeta_zeros[start:stop]
        x = x - x[0]
        y = np.full_like(x, i * 10 + 2)
        if once:
            plt.scatter(x[0], y[0], c="b", s=3, label="Zeta Zeros")
            once = False
        plt.scatter(x, y, c="b", s=3)

    # Plot the random numbers in 10 lines of 100 values each
    once = True
    for i in range(10):
        start = i * 100
        stop = start + 99
        x = random_array[start:stop]
        x = x - x[0]
        y = np.full_like(x, i * 10 + 4)
        if once:
            plt.scatter(x[0], y[0], c="r", s=3, label="Uniform Random\nNumbers")
            once = False
        plt.scatter(x, y, c="r", s=3)

    # Plot the GUE eigenvalues in 10 lines of 100 values each
    once = True
    for i in range(10):
        start = i * 100
        stop = start + 99
        x = eigvals[start:stop]
        x = x - x[0]
        y = np.full_like(x, i * 10 + 6)
        if once:
            plt.scatter(x[0], y[0], c="g", s=3, label="GUE Eigenvalues")
            once = False
        plt.scatter(x, y, c="g", s=3)

    plt.title("The Montgomery-Odlyzko Law")
    plt.xlabel("Imaginary Component of each Zeta Root")
    plt.ylabel("100 values per row")
    plt.xlim(0, 100)
    plt.xticks([])
    plt.legend(loc="upper right", framealpha=1.0, facecolor="white")
    plt.gca().yaxis.set_major_locator(MultipleLocator(10))
    plt.show()


if __name__ == "__main__":
    main()
